### ISSUE TITLE
Configurable devices

### ISSUE THREAD

**Issue by wmedrano** [wmedrano/rust-audio-io#4]
Currently opening devices based on some defaults.

The current defaults
```yaml
freqency: 44.1kHz
format: signed-16bit-audio
channels: 2
buffer_size: 4096 # How many samples are in each cycle
cycle_queue_size: 4 # How many cycles can be queued for read/write operation
```
